# -*- coding: utf-8 -*-
"""YOUTUBE TRANSCRIPT SUMMARIZER

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N3tpmkz0z-uzuquEqdKA7ncRq8Zy9m22
"""

!pip install -q transformers

!pip install -q youtube_transcript_api

!pip install summa

from transformers import pipeline
from youtube_transcript_api import YouTubeTranscriptApi

youtube_video = "https://www.youtube.com/watch?v=aOL7wzEIZSc"

video_id = youtube_video.split("=")[1]

video_id

from IPython.display import YouTubeVideo
YouTubeVideo(video_id)

YouTubeTranscriptApi.get_transcript(video_id)
transcript = YouTubeTranscriptApi.get_transcript(video_id)

transcript[0:5]

result = ""
for i in transcript:
    result += ' ' + i['text']
#print(result)
print(len(result))

summarizer = pipeline('summarization')

num_iters = int(len(result)/1000)
summarized_text = []
for i in range(0, num_iters + 1):
  start = 0
  start = i * 1000
  end = (i + 1) * 1000
  out = summarizer(result[start:end], min_length, max_length)
  out = out[0]
  out = out['summary_text']
  summarized_text.append(out)

text1 = summarized_text

print(summarized_text)

print(text1)

from summa.summarizer import summarize

text = str(text1)

print(text)

summarize(text, ratio = 0.5)

!pip install googletrans==3.1.0a0

from googletrans import Translator
translator = Translator()
out = translator.translate(text, dest='hi')
print(out)

from googletrans import Translator
translator = Translator()
out = translator.translate(text, dest='hi')
print(out.text)

from googletrans import Translator
translator = Translator()
out = translator.translate(text, dest='te')
print(out.text)

from googletrans import Translator
translator = Translator()
out = translator.translate(text, dest='ur')
print(out.text)